// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhsksvknbzpeznvsudek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoc2tzdmtuYnpwZXpudnN1ZGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTUwNTAsImV4cCI6MjA2OTY3MTA1MH0.m8WLWTL19LzDwhePXTSmeu9_MqFVPHyIYSbxEDNNIkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});